import AuthContextProvider from "@/app/modules/auth_provider";
import WebSocketProvider from "@/app/modules/ws_provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col md:flex-row h-full min-h-screen font-sans" >
        <AuthContextProvider>
          <WebSocketProvider>
            <div className="bodyDiv">
              <div className={inter.className}>{children}</div>
            </div>
          </WebSocketProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
